#ifndef MACROS_H_
#define MACROS_H_

#define SQRT2DIV2			(1.4142135623730950488016887242097F * 0.5F)
#define WINDOW_W			1600//1920//1280
#define WINDOW_H			900//1080//1024
#define VIEWFINDER			(WINDOW_H * 0.984375F)
#define VIEWFINDER_CENTER	(VIEWFINDER * 0.5F)
#define WINDOW_CENTER_Y		(WINDOW_H / 2)
#define WORLD_W				13000.0F
#define WORLD_H				WORLD_W//4500.0F
#define PLAYER_REND_Y_SHIFT	(VIEWFINDER * 0.5F * 0.875F)
#define PLAYER_SIZE			32//48
#define GUN_SIGHT_SIZE		67
#define BULLET_SIZE			16
#define DECELERATION		0.93F//0.995F
#define TICK_TIME			0x200000ULL//0x200000ULL
#define TICK_TIME_MS		(TICK_TIME / 1000000ULL)
#define ACCELERATION		6.25e-2F
#define PLAYER_VELOCITY		1.25F
#define RUN_VELOCITY		(PLAYER_VELOCITY * 2.0F)//.0F
#define ROTATION_SPEED		3.90625e-3F//1 / 256       .0F
#define TEXTURE_FILES_NUM	6
#define TEXTURE_TARGET_NUM	1
#define TEXTURES_NUM		(TEXTURE_FILES_NUM + TEXTURE_TARGET_NUM)
#define SIGHT_SQUARED   	(VIEWFINDER_CENTER * VIEWFINDER_CENTER + (VIEWFINDER_CENTER + PLAYER_REND_Y_SHIFT) * (VIEWFINDER_CENTER + PLAYER_REND_Y_SHIFT))
#define SIGHT_BACK_SQUARED	(VIEWFINDER_CENTER * VIEWFINDER_CENTER + (VIEWFINDER_CENTER - PLAYER_REND_Y_SHIFT) * (VIEWFINDER_CENTER - PLAYER_REND_Y_SHIFT))
#define FRAME_TIME			0x400000ULL//0x400000ULL
#define SEGMENTS_X			64U
#define SEGMENTS_Y			SEGMENTS_X
#define WORLD_SIZE			WORLD_W
#define SEGMENTS_SIZE		(WORLD_SIZE / (float)SEGMENTS_X)
#define MAX_PROJECTILES_NUM	1000
#define MAX_SEGM_BEINGS		50
#define MAX_BEINGS_NUM		(SEGMENTS_X * SEGMENTS_Y * MAX_SEGM_BEINGS / 4)
#define ANGLE_PARTS		    512
#define MIN_ANGLE           (2.0F * SDL_PI_F / (float)ANGLE_PARTS)

// #define BOUNDS_U			0.0F//(VIEW_H * 0.5F)
// #define BOUNDS_D			WORLD_H//(WORLD_H + VIEW_H * 0.5F)
// #define BOUNDS_R			WORLD_W//(WORLD_W + VIEW_W * 0.5F)
// #define BOUNDS_L			0.0F//(VIEW_W * 0.5F)

// #define SQRT2				1.4142135623730950488016887242097F
// #define WINDOW_CENTER_X		(WINDOW_W / 2)
// #define SCALE               2.0F
// #define SCALE_REVERSE       (1.0F / SCALE)
// #define WORLD_TEXTURE_SCALE 0.25F//6.25e-2F
// #define VIEW_W				((int)((VIEWFINDER_CENTER + PLAYER_REND_Y_SHIFT) * 2.0F * SQRT2))
// #define VIEW_H				((int)((VIEWFINDER_CENTER + PLAYER_REND_Y_SHIFT) * 2.0F * SQRT2))
// #define VIEW_CENTER_X		(VIEW_W * 0.5F)
// #define VIEW_CENTER_Y		(VIEW_H * 0.5F)
// #define PLAYER_RENDER_X		VIEW_CENTER_X//VIEW_W * 0.5F
// #define PLAYER_RENDER_Y		VIEW_CENTER_Y//VIEW_H * 0.5F
// #define SIGHT_ANGLE			(SDL_PI_F * 0.22F)
// #define SIGHT_BACK_ANGLE	SDL_PI_F

//#define MAX_SEGM_PROJECTILES	100
//#define MINIMAL_DELAY		(TICK_TIME >> 9)
//#define BOUNDS_DECELERATE   0.97F
//#define TURNING_DECELERATE  0.997F
//#define BODY_SIZE           48
//#define BARREL_SIZE         BODY_SIZE
#endif